"""Google Maps place-detail scraper.

Phase 2.1 — refactored to consume ``utils/selectors.py`` multi-candidate
fallbacks. To add a new candidate, edit selectors.py — do NOT edit this file.
"""

from __future__ import annotations

import asyncio
import logging
import re

from playwright.async_api import Page, TimeoutError as PWTimeout

from maps_cold_calling.models import Business
from maps_cold_calling.utils.phone import normalize as normalize_phone
from maps_cold_calling.utils.retries import retry_async_with_backoff
from maps_cold_calling.utils.selectors import (
    ADDRESS_BUTTON_SELECTORS,
    CATEGORY_BUTTON_SELECTORS,
    DETAIL_PANEL_SELECTORS,
    NAME_SELECTORS,
    PHONE_BUTTON_SELECTORS,
    RATING_SELECTORS,
    REVIEWS_SELECTORS,
    WEBSITE_SELECTORS,
    first_attr_match,
    first_locator,
    first_text_match,
)

LOG = logging.getLogger(__name__)

DEFAULT_TIMEOUT_MS = 20_000


# ───────────────────────── helpers ─────────────────────────


def _extract_lat_lng(url: str) -> tuple[float | None, float | None]:
    """Pull ``@lat,lng`` from the Maps URL hash, falling back to ``!3d!4d``."""
    m = re.search(r"@(-?\d+\.\d+),(-?\d+\.\d+)", url)
    if m:
        try:
            return float(m.group(1)), float(m.group(2))
        except ValueError:
            pass
    m2 = re.search(r"!3d(-?\d+\.\d+)!4d(-?\d+\.\d+)", url)
    if m2:
        try:
            return float(m2.group(1)), float(m2.group(2))
        except ValueError:
            pass
    return None, None


def _extract_place_id(url: str) -> str | None:
    """Find a ``ChIJ…`` place id anywhere in the URL.

    The token appears as ``!19sChIJ…`` or ``!1sChIJ…`` depending on layout.
    Searching anywhere in the URL is robust to Google's data-blob reordering.
    """
    m = re.search(r"(ChI[A-Za-z0-9_\-]+)", url)
    return m.group(1) if m else None


def _phone_digits_only(raw: str) -> str:
    """Strip non-digit/non-plus chars; full E.164 lives in ``utils/phone.py``."""
    return re.sub(r"[^\d+]", "", raw)


def _strip_address_label(s: str | None) -> str | None:
    """Google prepends ``Address: `` / ``Адреса: `` to the aria-label."""
    if not s:
        return s
    for prefix in ("Адреса: ", "Адреса:", "Address: ", "Address:"):
        if s.startswith(prefix):
            return s[len(prefix):].strip()
    return s.strip()


def _rating_from_aria(label: str) -> float | None:
    m = re.search(r"(\d+[.,]\d+)", label)
    if not m:
        return None
    try:
        return float(m.group(1).replace(",", "."))
    except ValueError:
        return None


# Kept for backwards-compat callers; the async signature is a historical
# artifact. Use the synchronous ``_rating_from_aria`` instead.
async def _rating_from_aria_async(label: str) -> float | None:  # pragma: no cover - alias
    return _rating_from_aria(label)


def _parse_int_from_text(t: str | None) -> int | None:
    if not t:
        return None
    digits = re.sub(r"[^\d]", "", t)
    if not digits:
        return None
    try:
        return int(digits)
    except ValueError:
        return None


# Aria-label of a 2025+ Maps reviews-only pill (e.g. "1.911 рецензија") carries
# the count as the only number. We also accept a combined label that embeds both
# the rating and the review count, e.g. "Звездица: 4,5 Рецензија: 581".
# Returns ``(rating, reviews_count)`` — either may be ``None`` if not parseable.
# NOTE: use ``\w*`` (with re.UNICODE) instead of explicit Cyrillic classes —
# Python's ``[a-zа-я]*`` exhibits a backtracking quirk after the ćirilic
# letter "ј" (U+0458) at end-of-string.
_REVIEWS_BLOCK_RE = re.compile(
    r"(?:рецензи\w*|reviews?)\s*:\s*([\d\.\s]+)",
    re.IGNORECASE | re.UNICODE,
)
_RATING_BLOCK_RE = re.compile(
    r"(?:звезд\w*|rating)\s*:\s*([\d.,]+)",
    re.IGNORECASE | re.UNICODE,
)
# "1.911 рецензија" — number followed by "recenz" / "реценз" / "utisak" / "review"
# (Serbian declines: рецензија, рецензије, рецензију, ...)
_REVIEWS_PHRASE_RE = re.compile(
    r"([\d\.\s]+)\s*(?:рецензи\w*|recenzij\w*|utisak\w*|reviews?)\b",
    re.IGNORECASE | re.UNICODE,
)
_THINSPACE = "\u202f"
_NARROW_NBSP = "\u00a0"


def _normalize_number(s: str) -> str:
    """Normalize a number from a Maps label: strip thousands separators and
    non-breaking spaces. Serbian UI shows integers like ``1.911`` and ``5.399``
    (dot as thousands sep), so we drop dots entirely before ``int()``.
    """
    s = s.replace(_THINSPACE, "").replace(_NARROW_NBSP, "").replace(" ", "").replace("\u00a0", "")
    # Drop dots — they're thousands separators in Serbian integers.
    # Commas are kept for floats (e.g. ``4,5``).
    s = s.replace(".", "")
    return s


def _parse_reviews_label(label: str | None) -> tuple[float | None, int | None]:
    """Parse a Maps reviews-related aria-label.

    Examples (Serbian UI):
        "1.911 рецензија"                        → (None, 1911)
        "615 рецензија"                          → (None, 615)
        "Звездица: 4,5 Рецензија: 581"           → (4.5, 581)
        "Звездица: 4,5 Рецензија: 1.589"         → (4.5, 1589)
        "Rating: 4.5 Reviews: 120"               → (4.5, 120)
        "5,0 od 5 zvezdica 312 recenzija"         → (5.0, 312)

    Returns ``(rating, reviews_count)`` — each independently may be ``None``.
    """
    if not label:
        return None, None
    s = label.strip()
    rating: float | None = None
    reviews: int | None = None

    m = _RATING_BLOCK_RE.search(s)
    if m:
        try:
            rating = float(m.group(1).replace(",", ".").replace(" ", ""))
        except ValueError:
            rating = None
    if rating is None:
        # Loose form: "5,0 od 5 zvezdica" or "Rating 4.5 out of 5"
        loose = re.search(r"([\d.,]+)\s*(?:od\s*\d+\s*)?(?:zvezd\w*|stars?)", s, re.IGNORECASE | re.UNICODE)
        if loose:
            try:
                rating = float(loose.group(1).replace(",", ".").replace(" ", ""))
            except ValueError:
                rating = None

    m = _REVIEWS_BLOCK_RE.search(s)
    if m:
        try:
            reviews = int(_normalize_number(m.group(1)))
        except ValueError:
            reviews = None

    if reviews is None:
        # Only use the loose phrase pattern when the label doesn't already
        # contain ":" — otherwise we get false matches like "4.5" in
        # "Rating: 4.5 Reviews: 120" being treated as reviews count.
        has_colon = ":" in s
        if not has_colon:
            m = _REVIEWS_PHRASE_RE.search(s)
            if m:
                try:
                    reviews = int(_normalize_number(m.group(1)))
                except ValueError:
                    reviews = None

    return rating, reviews


# ───────────────────────── main API ─────────────────────────


async def extract_business(
    page: Page,
    url: str,
    *,
    city: str | None = None,
    country: str | None = None,
    default_phone_region: str = "RS",
) -> Business | None:
    """Open a Maps place URL and extract a :class:`Business``.

    Wrapped with exponential backoff on Playwright/network errors. After
    ``max_attempts`` failures, returns ``None`` so the runner can skip
    cleanly.
    """

    async def _do_extract() -> Business | None:
        return await _extract_business_impl(page, url, city=city, country=country, default_phone_region=default_phone_region)

    wrapped = retry_async_with_backoff(max_attempts=3, base_s=2.0, max_s=8.0)(_do_extract)
    try:
        return await wrapped()
    except Exception as exc:  # noqa: BLE001 — final retry gave up
        LOG.warning("detail: gave up after retries on %s: %s", url[:120], exc)
        return None


async def _extract_business_impl(
    page: Page,
    url: str,
    *,
    city: str | None,
    country: str | None,
    default_phone_region: str,
) -> Business | None:
    """Inner body of ``extract_business``; no retry decoration.

    Returns ``None`` if the page does not look like a place detail.
    """
    LOG.info("detail: GET %s", url[:120])
    try:
        await page.goto(url, wait_until="domcontentloaded", timeout=DEFAULT_TIMEOUT_MS)
    except PWTimeout:
        LOG.warning("detail: navigation timed out: %s", url[:120])
        return None

    # Explicit wait — ``domcontentloaded`` fires before Maps paints its
    # place panel. We wait on the FIRST (most-reliable) selector. If Maps
    # renders with a different layout the next selector in the chain is
    # tried lazily via the extraction helpers below.
    try:
        await page.wait_for_selector(DETAIL_PANEL_SELECTORS[0], timeout=DEFAULT_TIMEOUT_MS)
    except PWTimeout:
        # The first selector is missing — try the others via first_locator
        # before giving up.
        panel = await first_locator(page, DETAIL_PANEL_SELECTORS)
        if panel is None:
            LOG.warning("detail: detail panel never appeared: %s", url[:120])
            return None

    # Name — first non-empty h1 inside the panel.
    name = await first_text_match(page, NAME_SELECTORS)
    if not name:
        LOG.warning("detail: no name found at %s", url[:120])
        return None

    # Phone — raw digits kept for forensics; E.164 is what import systems consume.
    phone_raw: str | None = None
    phone_e164: str | None = None
    phone_aria = await first_attr_match(page, PHONE_BUTTON_SELECTORS, "aria-label")
    if phone_aria:
        phone_raw = _phone_digits_only(phone_aria)
        phone_e164 = normalize_phone(phone_aria, default_region=default_phone_region)
        if phone_e164 is None and phone_raw:
            LOG.debug("phone: %r could not be normalized to E.164", phone_aria)

    # Website
    website = await first_attr_match(page, WEBSITE_SELECTORS, "href")

    # Address — strip Google's localized "Address: " prefix.
    address = await first_attr_match(page, ADDRESS_BUTTON_SELECTORS, "aria-label")
    address = _strip_address_label(address)

    # Category
    category = await first_attr_match(page, CATEGORY_BUTTON_SELECTORS, "aria-label")

    # Rating — first aria-label that parses as a float.
    rating: float | None = None
    for sel in RATING_SELECTORS:
        label = await first_attr_match(page, [sel], "aria-label")
        if label:
            rating = _rating_from_aria(label)
            if rating is not None:
                break

    # Reviews count — and possibly a missing rating on the same label.
    reviews_count: int | None = None
    for sel in REVIEWS_SELECTORS:
        rev_label = await first_attr_match(page, [sel], "aria-label")
        if not rev_label:
            continue
        rl_rating, rl_reviews = _parse_reviews_label(rev_label)
        if rl_reviews is not None:
            reviews_count = rl_reviews
            if rating is None and rl_rating is not None:
                rating = rl_rating
            break

    # Coordinates + place_id from the final URL (post-redirect).
    final_url = page.url
    lat, lng = _extract_lat_lng(final_url)
    place_id = _extract_place_id(final_url)

    biz = Business(
        name=name,
        address=address,
        city=city,
        country=country,
        phone_raw=phone_raw,
        phone_e164=phone_e164,
        website=website,
        category=category,
        rating=rating,
        reviews_count=reviews_count,
        latitude=lat,
        longitude=lng,
        google_place_id=place_id,
        google_maps_url=final_url,
        source="maps",
    )
    LOG.info(
        "detail: +%s [%s] phone=%s website=%s",
        biz.name[:40],
        ("%.1f★" % biz.rating) if biz.rating is not None else "—",
        "yes" if biz.phone_raw else "no",
        "yes" if biz.website else "no",
    )
    await asyncio.sleep(0)  # yield once; later phases add jitter
    return biz


__all__ = ["extract_business"]
